// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPD0HpB_iyc9V4gmpyG9hq6n7lv1yy97Q',
    appId: '1:580452801538:web:a76104365c2604b9d1db1b',
    messagingSenderId: '580452801538',
    projectId: 'myfirebaseapp-bfad7',
    authDomain: 'myfirebaseapp-bfad7.firebaseapp.com',
    storageBucket: 'myfirebaseapp-bfad7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeGnoaDJuJ9zTwPIM5_-vjzdy_Dp-ws_w',
    appId: '1:580452801538:android:83aa80995f68260dd1db1b',
    messagingSenderId: '580452801538',
    projectId: 'myfirebaseapp-bfad7',
    storageBucket: 'myfirebaseapp-bfad7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzUc8TnfiQ-NVkYmgg3rCx_kVXNWAjHU',
    appId: '1:580452801538:ios:a83b326ae35b4105d1db1b',
    messagingSenderId: '580452801538',
    projectId: 'myfirebaseapp-bfad7',
    storageBucket: 'myfirebaseapp-bfad7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzUc8TnfiQ-NVkYmgg3rCx_kVXNWAjHU',
    appId: '1:580452801538:ios:a83b326ae35b4105d1db1b',
    messagingSenderId: '580452801538',
    projectId: 'myfirebaseapp-bfad7',
    storageBucket: 'myfirebaseapp-bfad7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPD0HpB_iyc9V4gmpyG9hq6n7lv1yy97Q',
    appId: '1:580452801538:web:893e06d2fb56256ed1db1b',
    messagingSenderId: '580452801538',
    projectId: 'myfirebaseapp-bfad7',
    authDomain: 'myfirebaseapp-bfad7.firebaseapp.com',
    storageBucket: 'myfirebaseapp-bfad7.firebasestorage.app',
  );
}
